[env:esp32dev]
platform = espressif32@^6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit GFX Library@^1.11.11
  adafruit/Adafruit SSD1306@^2.5.13
lib_extra_dirs =
  ST Servo
